### ISSUE TITLE
Only male voices?

### ISSUE THREAD

**Issue by ghost** [TUD-STKS/VocalTractLab-dev#18]
version 2.3

Synthesis Models > Anatomy parameters: the resulting voice always sounds like an adult male even if I select female or child.
Is this a known limitation, or am I just using it wrong?

**Comment by Simon-Stone** [comment]
You stumbled into the danger zone. :-) 

As pointed out in the manual, this dialog should be considered experimental. There are a number of things to know when using it and it is easy to break things.

Some of the issues you may have been having in brief:

- When you change the anatomy, all vocal tract shapes are invalidated and discarded, so you won't be able to synthesize connected utterances unless you define new shapes for the new anatomy.
- Maybe you forgot to adapt the glottis parameters, especially the fundamental frequency? This has quite a strong impact on the voice identity perception.
- You need to make sure the vocal tract configuration shown in the vocal tract dialog is actually used for the synthesis. If you are using the time domain simulation, click "Set Area Function" before synthesizing.

You can find more information in the publication that this dialog was implemented for:

Birkholz P, Kröger BJ (2007). Simulation of vocal tract growth for articulatory speech synthesis. In Proc. of the 16th International Congress of Phonetic Sciences (ICPhS 2007), pp. 377–380, Saarbrücken, Germany [[pdf](https://vocaltractlab.de/publications/birkholz-2007-icphs.pdf)]


I hope this helps. Since this dialog is considered experimental, I will close this issue.

**Comment by ghost** [comment]
Thanks for the detailed explanation and the link, very useful.
I was surprised by the high quality of the samples on the website, you've been doing some seriously awesome work!

**Comment by Simon-Stone** [comment]
Thank you very much, that's very kind! We are also quite happy about the progress and there are a few things coming down the pipe that should improve the quality even more. We hope that opening up the synthesizer as a true open source project will accelerate things even further.
